### ISSUE TITLE
check for duplicate objects

### ISSUE THREAD

**Issue by marcelh-gh** [rogeriopvl/gulp-jsonlint#57]
it would be nice if duplicate object keys would be detected

**Comment by rogeriopvl** [comment]
@marcelh-gh `gulp-jsonlint` is just a wrapper around `jsonlint`. Feature requests should be made to the [jsonlint](https://github.com/zaach/jsonlint) project.

**Comment by marcelh-gh** [comment]
okey-dokey ;-) thx!
